// <auto-generated />
using System;
using BankProfiles.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankProfiles.Web.Data.Migrations
{
    [DbContext(typeof(BankDbContext))]
    [Migration("20260418070914_AddBankOnboardingSubmissions")]
    partial class AddBankOnboardingSubmissions
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("LastViewedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("BankId");

                    b.HasIndex("BankCode")
                        .IsUnique();

                    b.HasIndex("ViewCount");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.BankOnboardingSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<string>("ApprovedBankCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ProposedBankName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ProposedCountryCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("ProposedWebsiteUrl")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime?>("ReviewedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<string>("SubmissionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubmitterIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("SubmissionId");

                    b.HasIndex("ApprovedBankCode");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.HasIndex("SubmitterIP", "SubmittedDate");

                    b.ToTable("BankOnboardingSubmissions");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.BankRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RatingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("RatingValue")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<int?>("UserRatingSubmissionId")
                        .HasColumnType("int");

                    b.HasKey("RatingId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("UserRatingSubmissionId");

                    b.HasIndex("BankId", "CriteriaId");

                    b.ToTable("BankRatings");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.BankSnapshot", b =>
                {
                    b.Property<long>("SnapshotId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("SnapshotId"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("EventSequenceUpTo")
                        .HasColumnType("bigint");

                    b.Property<string>("ProfileJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SnapshotId");

                    b.HasIndex("BankCode", "EventSequenceUpTo");

                    b.ToTable("BankSnapshots");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.FeedbackSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubmitterIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("SubmissionId");

                    b.HasIndex("SubmissionDate");

                    b.HasIndex("SubmitterIP");

                    b.HasIndex("SubmitterIP", "SubmissionDate");

                    b.ToTable("FeedbackSubmissions");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.MetricEvent", b =>
                {
                    b.Property<long>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("EventId"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("EventSequence")
                        .HasColumnType("bigint");

                    b.Property<int>("EventVersion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MetricType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("MetricValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("EventId");

                    b.HasIndex("BankCode");

                    b.HasIndex("BankCode", "EventSequence")
                        .IsUnique();

                    b.HasIndex("BankCode", "MetricName", "CreatedDate");

                    b.ToTable("MetricEvents");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.MetricFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MetricCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubmitterIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("SuggestedValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BankId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("MetricFeedbacks");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingCriteria", b =>
                {
                    b.Property<int>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CriteriaId");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("RatingCriterias");

                    b.HasData(
                        new
                        {
                            CriteriaId = 1,
                            DisplayOrder = 1,
                            Name = "Service"
                        },
                        new
                        {
                            CriteriaId = 2,
                            DisplayOrder = 2,
                            Name = "Fees"
                        },
                        new
                        {
                            CriteriaId = 3,
                            DisplayOrder = 3,
                            Name = "Convenience"
                        },
                        new
                        {
                            CriteriaId = 4,
                            DisplayOrder = 4,
                            Name = "Digital Services"
                        },
                        new
                        {
                            CriteriaId = 5,
                            DisplayOrder = 5,
                            Name = "Customer Support"
                        });
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("OverallRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("HistoryId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("BankId", "CriteriaId", "RecordedDate");

                    b.ToTable("RatingHistories");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.UserRatingSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<decimal>("ConvenienceRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("CustomerSupportRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("DigitalServicesRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("FeesRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<decimal>("ServiceRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubmitterIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("SubmissionId");

                    b.HasIndex("BankId");

                    b.HasIndex("SubmittedDate");

                    b.HasIndex("SubmitterIP", "SubmittedDate");

                    b.ToTable("UserRatingSubmissions");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.ViewHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("HistoryId");

                    b.HasIndex("BankId", "RecordedDate");

                    b.ToTable("ViewHistory");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.BankRating", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany("BankRatings")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankProfiles.Web.Data.Entities.RatingCriteria", "Criteria")
                        .WithMany("BankRatings")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("BankProfiles.Web.Data.Entities.UserRatingSubmission", "UserRatingSubmission")
                        .WithMany("AppliedRatings")
                        .HasForeignKey("UserRatingSubmissionId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Bank");

                    b.Navigation("Criteria");

                    b.Navigation("UserRatingSubmission");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.MetricFeedback", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingHistory", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany("RatingHistories")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankProfiles.Web.Data.Entities.RatingCriteria", "Criteria")
                        .WithMany("RatingHistories")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.UserRatingSubmission", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany("UserRatingSubmissions")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.ViewHistory", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany("ViewHistories")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.Bank", b =>
                {
                    b.Navigation("BankRatings");

                    b.Navigation("RatingHistories");

                    b.Navigation("UserRatingSubmissions");

                    b.Navigation("ViewHistories");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingCriteria", b =>
                {
                    b.Navigation("BankRatings");

                    b.Navigation("RatingHistories");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.UserRatingSubmission", b =>
                {
                    b.Navigation("AppliedRatings");
                });
#pragma warning restore 612, 618
        }
    }
}
