// <auto-generated />
using System;
using BankProfiles.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankProfiles.Web.Data.Migrations
{
    [DbContext(typeof(BankDbContext))]
    partial class BankDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.Bank", b =>
                {
                    b.Property<int>("BankId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BankId"));

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<DateTime?>("LastViewedDate")
                        .HasColumnType("datetime2");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("BankId");

                    b.HasIndex("BankCode")
                        .IsUnique();

                    b.HasIndex("ViewCount");

                    b.ToTable("Banks");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.BankRating", b =>
                {
                    b.Property<int>("RatingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RatingId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RatingDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<decimal>("RatingValue")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.HasKey("RatingId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("BankId", "CriteriaId");

                    b.ToTable("BankRatings");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.FeedbackSubmission", b =>
                {
                    b.Property<int>("SubmissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubmissionId"));

                    b.Property<DateTime>("SubmissionDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubmitterIP")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.HasKey("SubmissionId");

                    b.HasIndex("SubmissionDate");

                    b.HasIndex("SubmitterIP");

                    b.HasIndex("SubmitterIP", "SubmissionDate");

                    b.ToTable("FeedbackSubmissions");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.MetricFeedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int?>("BankId")
                        .HasColumnType("int");

                    b.Property<string>("CurrentValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("MetricCategory")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReviewNotes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("SubmittedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("SubmitterIP")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("SuggestedValue")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BankId");

                    b.HasIndex("Status");

                    b.HasIndex("SubmittedDate");

                    b.ToTable("MetricFeedbacks");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingCriteria", b =>
                {
                    b.Property<int>("CriteriaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CriteriaId"));

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CriteriaId");

                    b.HasIndex("DisplayOrder");

                    b.ToTable("RatingCriterias");

                    b.HasData(
                        new
                        {
                            CriteriaId = 1,
                            DisplayOrder = 1,
                            Name = "Service"
                        },
                        new
                        {
                            CriteriaId = 2,
                            DisplayOrder = 2,
                            Name = "Fees"
                        },
                        new
                        {
                            CriteriaId = 3,
                            DisplayOrder = 3,
                            Name = "Convenience"
                        },
                        new
                        {
                            CriteriaId = 4,
                            DisplayOrder = 4,
                            Name = "Digital Services"
                        },
                        new
                        {
                            CriteriaId = 5,
                            DisplayOrder = 5,
                            Name = "Customer Support"
                        });
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<int>("CriteriaId")
                        .HasColumnType("int");

                    b.Property<decimal>("OverallRating")
                        .HasPrecision(4, 2)
                        .HasColumnType("decimal(4,2)");

                    b.Property<DateTime>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.HasKey("HistoryId");

                    b.HasIndex("CriteriaId");

                    b.HasIndex("BankId", "CriteriaId", "RecordedDate");

                    b.ToTable("RatingHistories");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.ViewHistory", b =>
                {
                    b.Property<int>("HistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HistoryId"));

                    b.Property<int>("BankId")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<long>("ViewCount")
                        .HasColumnType("bigint");

                    b.HasKey("HistoryId");

                    b.HasIndex("BankId", "RecordedDate");

                    b.ToTable("ViewHistory");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.BankRating", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany("BankRatings")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankProfiles.Web.Data.Entities.RatingCriteria", "Criteria")
                        .WithMany("BankRatings")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.MetricFeedback", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany()
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingHistory", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany("RatingHistories")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BankProfiles.Web.Data.Entities.RatingCriteria", "Criteria")
                        .WithMany("RatingHistories")
                        .HasForeignKey("CriteriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bank");

                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.ViewHistory", b =>
                {
                    b.HasOne("BankProfiles.Web.Data.Entities.Bank", "Bank")
                        .WithMany("ViewHistories")
                        .HasForeignKey("BankId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.Bank", b =>
                {
                    b.Navigation("BankRatings");

                    b.Navigation("RatingHistories");

                    b.Navigation("ViewHistories");
                });

            modelBuilder.Entity("BankProfiles.Web.Data.Entities.RatingCriteria", b =>
                {
                    b.Navigation("BankRatings");

                    b.Navigation("RatingHistories");
                });
#pragma warning restore 612, 618
        }
    }
}
